---
title: "FUV Spring 2023 Reading Group: Blockchain and ChatGPT"
date: "Last update: 2023-03-06"
output: html_document
---


This is a **very informal** reading group.

We will learn the basics of Blockchain and ChatGPT.
The main idea is to understand the technologies and implications of them.
That means we will cover certain technical aspects.
High-level impacts have been discussed a lot in the news so we want to see what's
beneath.
The **most optimistic** hope is to innovate and do something novel with these.
Perhaps, talented students would want to take advantage and dream big on this.

Although we hope to learn things, as we are not experts, the meetings could be
messy. At some point, we may have to sit down and read the texts together on the big screen.

For info about previous reading groups, please go to https://github.com/sonv/reading-group.

## Key information

**Time**: Fridays, 9am-10am

**Place**: CR 502 (except further notices)

**Core members** (responsible to lead):  Tran Vinh Linh, Hieu Nguyen, Minh Doan, Lan Nguyen, Graeme Walker, Truong-Son Van

Everyone who's not a core member is encouraged to lead if they think they can 
do it.


## Materials

We will follow a course on MIT Open Courseware called Blockchain and Money.
All the materials (including reading materials, videos and slides) are available here:

https://ocw.mit.edu/courses/15-s12-blockchain-and-money-fall-2018/

The syllabus will be roughly the same but we will go with higher speed (hopefully)
as this is not supposed to be a class but a reading seminar.

A comprehensive book for a course taught on Coursera and at Princeton.

[Bitcoin and Cryptocurrency Technologies](https://bitcoinbook.cs.princeton.edu/)


[Original paper by Satoshi Nakamoto](https://bitcoin.org/bitcoin.pdf)

### YouTube videos

[Public Key Cryptography](https://youtu.be/GSIDS_lvRv4)

[SHA: Secure Hashing Algorithm](https://youtu.be/DMtFhACPnTY)

[Digital Signature](https://youtu.be/s22eJ1eVLTU)

[How does Bitcoin work](https://youtu.be/bBC-nXj3Ng4)


## How to encrypt/decrypt file using openssl

To generate a private key using RSA

    openssl genpkey -algorithm RSA -out private_key.pem -pkeyopt rsa_keygen_bits:2048

To generate public key

    openssl rsa -pubout -in private_key.pem -out public_key.pem

To encode a file

    openssl rsautl -encrypt -pubin -inkey public_key.pem -in test -out test.enc

To decode a file
    
    openssl rsautl -decrypt -ssl -inkey private_key.pem -in test.enc -out test.dec


## Smart contracts

[What is Ethereum? A Beginner's Explanation in Plain English (Skipped the short recap on BitCoin)](https://www.youtube.com/watch?t=85&v=jxLkbJozKbY)

[Ethereum Wallets Explained Simply (Smart Contracts, Gas, Transactions)](https://www.youtube.com/watch?v=qLZ1IoezucE)

[MIT Course - Lecture 6 - Last point from Law Professor Larry Lessig](https://www.youtube.com/watch?v=JPkgJwJHYSc)

MIT Course - Lecture 6 - BitCoin vs. Ethereum (Technical features & overall comparison)

[Proof of Stake](https://www.youtube.com/watch?v=M3EFi_POhps)

State of the DApps does not exist anymore, but there are others that serve similar functions of DApps directory/store/review such as 
DappRadar - The World’s Dapp Store | Blockchain Dapps Ranked or DappReview - Discover your next favourite fecentralized App.

## Hash functions
[Slides](Block-Chain/Hash_functions.pdf)

## Tentative Schedule

We skip some weeks due to breaks/important meetings.

| Date     | Leader | Topic                      |
| -------- | ------ | -------------------------- |
| March 10 | Son    | Intro to technical details |
| March 24 | Son    | Intro to technical details |
| April 14  | Lan    | Smart contracts            |
| April 29 | Linh | Scalabilitf                           |
| May 05| Hieu |   Hash functions                          |
